version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_USER: root
      MYSQL_PASSWORD: xxxxx
      MYSQL_DATABASE: weather_production
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /my/local/path/rails/meteo-rails:/usr/src/meteo-rails
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RACK_ENV: production
      RAILS_ENV: production  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions  
