# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a54616fca534eafcf01b742d9bbf92506e240cc82723b9f5653dac26758097cc4b3d6ed7ee4420cd9348072fdfcfedf76e8a97e7b351d21d59d898c02169a4

test:
  secret_key_base: c3488de3255ae7f13b1ba9ab5125741cf13374aa7d54a04a54802b9ee98a36e69da83cfbedbe923995bfc0cfc230d75c3c8a3843bfc6d5adde6c815eb05a1774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
